// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Stand alone stickman":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Stickman handshake":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f 2 f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . f f f f f f f f f f f . . . 
. . f f . f f f f f . f f . . . 
. . f f . f f f f f . f f . . . 
. . f f . f f f f f . f f . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . 2 f 2 f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f f f f f f f f f . . . . 
. . . f f f f f f f f f . . . . 
. . . f f f f f f f f f . . . . 
. . . f f f f f f f f f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . f f f f f . . . . . . . 
. . . . f f f f f . . . . . . . 
. . . f f . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . f f f f f . . . . . . . 
. . . f f f f f f . . . . . . . 
. . . f f . f f f . . . . . . . 
. . . f . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f f f f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . f . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . f f . . f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . . f f f f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f f f f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . f f . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f f f f f f . . . . . . . 
. . f f f f f f f . . . . . . . 
. . f f f . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . 2 f 2 f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . f f f f f f f . . . . . . 
. . f f f f f f f f . . . . . . 
. . f f . . f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f . f . . . . . . . 
. . . . . . f . f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f 2 f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . f f f f f f f f . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f f f f f f f f f . . . . 
. . . f f f f f f f f f . . . . 
. . . f f f f f f f f f . . . . 
. . . f f f f f f f f f . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`];
            case "Walking Stickman":
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f . f f f f f . . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . f f . f f . . . . . . . 
. . . f f f . f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f . f f f f f . . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . f f . f f . . . . . . . 
. . . f f f . f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f . f f f f f . . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . f f . f f . . . . . . . 
. . . f f f . f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . f . f f f f f . . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . . f f . f f . . . . . . . 
. . . f f f . f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`];
            case "throwing ball":
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . 7 f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . 7 f f . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . f f f . . . . . 
. . . 7 f f . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . 7 f f f . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . f f f f f f f f . . . . . 
. 7 f f . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . f f f f f f f f f . . . . . 
. . 7 f f f f f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . f 7 . . . f f f . . . . . 
. . . f f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . f 7 . . f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . 7 f . . f f f . . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . 7 f . . . . f f f . . . . . 
. . . f f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. 7 . . . . . . f f f . . . . . 
. . f f f f f f f f f . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
7 . . . . . . . f f f . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f f f f f f f . . . . . 
. . . f f . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f . . f f f . . . . . 
. . . . f . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f . f f f . . . . . 
. . . . f f . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f 2 f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
`];
            case "jumping jack":
            case "anim4":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
f f f . . f f f f f . . f f f . 
f f . . . f f f f f . . . f f . 
f . . . . f f f f f . . . . f . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
f f f f f f f f f f f f f f f f 
f f . . . f f f f f . . . f f f 
f . . . . f f f f f . . . . f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
f f . . . . f f f . . . . . f f 
f f f f f f f f f f f f f f f f 
f . . . . f f f f f . . . . . f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
f . . . f f f f f f f . . . . f 
f f . . . . f f f . . . . . f f 
. f f f f f f f f f f f f f f . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
f . . . f f f f f f f . . . . f 
f f . . f f f f f f f . . . f f 
f f f . . . f f f . . . . f f f 
. f f f f f f f f f f f f f f . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
f . . . f f f f f f f . . . . f 
f f . . f f f f f f f . . . f f 
. f f . . . f f f . . . . f f . 
. . f f f f f f f f f f f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
f . . . f f f f f f f . . . . f 
f f . . . . f f f . . . . . f f 
f f f f f f f f f f f f f f f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
f . . . . . f f f . . . . . . f 
f f f f f f f f f f f f f f f f 
f f . . . f f f f f . . . . f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f f . 
. f f f . f f f f f . . f f f . 
f f f . . f f f f f . . . f f f 
f f f . . f f f f f . . . f f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f f . 
. f f f . f f f f f . . f f f . 
. f f f . f f f f f . . f f f . 
. f f f . f f f f f . . f f f . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f f . 
. f f f . f f f f f . . f f f . 
. f f f f f f f f f . . f f f f 
. f f f f f f f f f . . f f f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f f . 
. f f f . f f f f f . . f f f . 
. f f f . f f f f f . . f f f . 
. f f . . f f f f f . . f f f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f f . 
. f f . . f f f f f . . f f f . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`];
            case "flinch":
            case "anim5":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
f f f . . f f f f f . . f f f . 
f f . . . f f f f f . . . f f . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
f f f . . f f f f f . . f f f . 
f f . . . f f f f f . . . f f f 
f . . . . f f f f f . . . . f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f 2 f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
f f f f f f f f f f f f f f f . 
f f . . . f f f f f . . . f f f 
f . . . . f f f f f . . . . f f 
. . . . . f f f f f . . . . . f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
f . . . . . f f f . . . . . . f 
f f f f f f f f f f f f f f f f 
f . . . . f f f f f . . . . . f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f f f f f f f . . . . . 
f . . . f f f f f f f . . . . f 
f f . . . . f f f . . . . . f f 
f f f f f f f f f f f f f f f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f 2 f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
f . . . . . f f f . . . . . . f 
f f f f f f f f f f f f f f f f 
f . . . . f f f f f . . . . . f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 2 f 2 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
f f f f f f f f f f f f f f f f 
f f . . . f f f f f . . . . f f 
f . . . . f f f f f . . . . . f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . f f f f f f f f f f f f . . 
. f f . . f f f f f . . . f f . 
f f f . . f f f f f . . . f f f 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f 2 f 2 f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. f f f f f f f f f f f f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. f f . . f f f f f . . f f . . 
. . . . . f f f f f . . . . . . 
. . . . . f f . f f . . . . . . 
. . . . . f f . f f . . . . . . 
`];
            case "picking up ball":
            case "anim6":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . 7 . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . 7 . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f 2 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
. . . . . . . f f f . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . 7 . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . f f f f f 2 f . . . 
. . . . . . f f f f f f f . . . 
. . . . . . . f f f . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . f . . . . 
. . . . . . f f f . . f f . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f . f f . . . 7 . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f 2 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
. . . . . . . f f f . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . f f . . . 
. . . . . . f f f . . . f f . . 
. . . . . f f f f f . . . 7 . . 
. . . . f f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . f f f f f 2 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . . . f f f . . f f . . . 
. . . . . . f f f . . . f f . . 
. . . . . . f f f . . . . 7 . . 
. . . . . f f f f f . . . . . . 
. . . . f f f . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . . . f f f . . f f . . . 
. . . . . . f f f . . . 7 . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f f . f f . . . . 
. . . . . . f f f . . 7 . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f f . 7 . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . f f f 7 . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . . f f f . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
